# Generates test/fixtures/nbody_reference.jl: reference trajectories from
# upstream NbodyGradient.jl v0.2.3 (7d9225b) used by the kernel-equivalence
# gate in test/nbody.jl. Our merged AHL21 kernels must reproduce these states
# from the same Cartesian ICs, masses, GNEWT, and step count.
#
# Run in an environment with upstream NbodyGradient dev-installed, e.g.:
#   julia -e 'using Pkg; Pkg.activate("nbenv"); Pkg.develop(path="NbodyGradient.jl")'
#   julia --project=nbenv test/fixtures/generate_nbody_reference.jl
#
# The systems are element-realistic (Kepler-36-like and TRAPPIST-1-like
# subsets, from the values shipped in upstream's tests/docs), but the gate is
# on the *kernels*: ICs are recorded as Cartesian states, so upstream's
# element conventions never enter the comparison.

using NbodyGradient
using Printf

fmt(x) = @sprintf("%.17g", x)
function dump_mat(io, name, m::AbstractMatrix)
    print(io, name, " = [")
    for r in 1:size(m, 1)
        print(io, join((fmt(m[r, c]) for c in 1:size(m, 2)), " "))
        r < size(m, 1) && print(io, "; ")
    end
    print(io, "]")
end

cases = []

# --- Kepler-36-like: star + two low-mass planets near 7:6 ---
let
    t0 = 0.0
    star = Elements(m=1.071)
    b = Elements(m=1.32e-5, P=13.83989, t0=2.0, ecosω=0.02, esinω=-0.01, I=π/2, Ω=0.0)
    c = Elements(m=2.42e-5, P=16.23855, t0=5.0, ecosω=-0.015, esinω=0.005, I=π/2 + 0.01, Ω=0.05)
    ic = ElementsIC(t0, 3, star, b, c)
    push!(cases, (name="kepler36", h=0.7, ic=ic))
end

# --- TRAPPIST-1-like: low-mass star + three tightly packed planets ---
let
    t0 = 0.0
    star = Elements(m=0.089)
    b = Elements(m=4.6e-6, P=1.510826, t0=0.2, ecosω=0.005, esinω=0.002, I=π/2, Ω=0.0)
    c = Elements(m=3.5e-6, P=2.421937, t0=0.9, ecosω=-0.003, esinω=0.004, I=π/2 - 0.004, Ω=0.02)
    d = Elements(m=1.3e-6, P=4.049219, t0=1.4, ecosω=0.002, esinω=-0.006, I=π/2 + 0.006, Ω=-0.03)
    ic = ElementsIC(t0, 4, star, b, c, d)
    push!(cases, (name="trappist1", h=0.075, ic=ic))
end

snap_steps = [1, 10, 100, 1000]

open(joinpath(@__DIR__, "nbody_reference.jl"), "w") do io
    println(io, "# Generated by generate_nbody_reference.jl from NbodyGradient.jl v0.2.3 (7d9225b).")
    println(io, "# DO NOT EDIT — regenerate with the script instead.")
    println(io, "const NBODY_GNEWT = ", fmt(NbodyGradient.GNEWT))
    println(io, "const NBODY_SNAP_STEPS = ", snap_steps)
    println(io, "const NBODY_CASES = [")
    for case in cases
        s = State(case.ic)
        n = s.n
        println(io, "(name = \"", case.name, "\", h = ", fmt(case.h), ",")
        println(io, " m = [", join((fmt(mi) for mi in s.m), ", "), "],")
        dump_mat(io, " x0", copy(s.x)); println(io, ",")
        dump_mat(io, " v0", copy(s.v)); println(io, ",")
        println(io, " snaps = [")
        nstep = 0
        for target in snap_steps
            while nstep < target
                ahl21!(s, case.h)
                nstep += 1
            end
            print(io, " (")
            dump_mat(io, "x", copy(s.x)); print(io, ", ")
            dump_mat(io, "v", copy(s.v))
            println(io, "),")
        end
        println(io, " ]),")
    end
    println(io, "]")
end
println("wrote nbody_reference.jl")
