# Generates test/fixtures/v1_reference.jl: reference observable values
# computed with PlanetOrbits **v1** (0.11.x), against which the v2
# reimplementation is regression-tested (KeplerianApprox must reproduce v1's
# math exactly for these model classes).
#
# Run against a v1 checkout, from this directory:
#     julia --project=<path-to-v1-checkout> generate_v1_reference.jl
#
# The output file is checked in; regenerate only if the case list changes.

using PlanetOrbits

@assert !isdefined(PlanetOrbits, :System) "this script must run against PlanetOrbits v1"

const mjup = PlanetOrbits.mjup2msol_IAU

# Epoch pattern: fractions of the orbital period around tp, including
# periastron (0.0) and apoastron (0.5) exactly.
const PHASES = [-0.15, 0.0, 0.12, 0.37, 0.5, 0.83, 1.4]

casedefs = [
    (name="kep-circular", kind=:kep,
     params=(a=1.5, e=0.0, i=0.2, ω=0.0, Ω=0.0, tp=58800.0, M=1.0), Mp=nothing),
    (name="kep-mid", kind=:kep,
     params=(a=8.0, e=0.35, i=0.7, ω=1.1, Ω=2.2, tp=58500.0, M=1.6), Mp=nothing),
    (name="kep-ecc", kind=:kep,
     params=(a=3.2, e=0.93, i=1.4, ω=-0.5, Ω=4.0, tp=58900.0, M=0.6), Mp=nothing),
    (name="kep-face-on", kind=:kep,
     params=(a=5.0, e=0.2, i=0.0, ω=0.4, Ω=1.9, tp=58700.0, M=2.2), Mp=nothing),
    (name="kep-edge-on", kind=:kep,
     params=(a=5.0, e=0.5, i=π/2, ω=2.9, Ω=0.3, tp=58600.0, M=1.1), Mp=nothing),
    (name="visual-1", kind=:visual,
     params=(a=8.0, e=0.1, i=0.5, ω=1.1, Ω=2.2, tp=58849.0, M=1.1, plx=24.5), Mp=5mjup),
    (name="visual-ecc", kind=:visual,
     params=(a=2.1, e=0.85, i=1.2, ω=0.7, Ω=5.5, tp=59100.0, M=0.9, plx=112.0), Mp=0.08),
    (name="absvis-1", kind=:absvis,
     params=(a=8.0, e=0.1, i=0.5, ω=1.1, Ω=2.2, tp=58849.0, M=1.1, plx=24.5,
             ra=45.0, dec=-30.0, pmra=100.0, pmdec=-50.0, rv=25e3, ref_epoch=57388.5),
     Mp=5mjup),
    (name="absvis-2", kind=:absvis,
     params=(a=1.2, e=0.4, i=0.9, ω=2.0, Ω=1.0, tp=58900.0, M=0.7, plx=210.0,
             ra=310.4, dec=67.8, pmra=-2500.0, pmdec=1800.0, rv=-31e3, ref_epoch=58849.0),
     Mp=0.02),
]

results = Any[]
for c in casedefs
    o = orbit(; c.params...)
    P = period(o)
    epochs = c.params.tp .+ P .* PHASES
    sols = [orbitsolve(o, t) for t in epochs]
    data = Dict{Symbol,Any}(
        :posx => [posx(s) for s in sols],
        :posy => [posy(s) for s in sols],
        :posz => [posz(s) for s in sols],
        :velx => [velx(s) for s in sols],
        :vely => [vely(s) for s in sols],
        :velz => [velz(s) for s in sols],
        :radvel => [radvel(s) for s in sols],
    )
    if c.kind in (:visual, :absvis)
        merge!(data, Dict{Symbol,Any}(
            :raoff => [raoff(s) for s in sols],
            :decoff => [decoff(s) for s in sols],
            :pmra => [pmra(s) for s in sols],
            :pmdec => [pmdec(s) for s in sols],
            :projectedseparation => [projectedseparation(s) for s in sols],
            :posangle => [posangle(s) for s in sols],
            # reflex (primary about the barycentre) via v1 mass overloads
            :raoff_reflex => [raoff(s, c.Mp) for s in sols],
            :decoff_reflex => [decoff(s, c.Mp) for s in sols],
            :pmra_reflex => [pmra(s, c.Mp) for s in sols],
            :pmdec_reflex => [pmdec(s, c.Mp) for s in sols],
            :radvel_reflex => [radvel(s, c.Mp) for s in sols],
        ))
    end
    if c.kind == :absvis
        merge!(data, Dict{Symbol,Any}(
            :comp_ra2 => [s.compensated.ra2 for s in sols],
            :comp_dec2 => [s.compensated.dec2 for s in sols],
            :comp_pmra2 => [s.compensated.pmra2 for s in sols],
            :comp_pmdec2 => [s.compensated.pmdec2 for s in sols],
            :comp_rv2 => [s.compensated.rv2 for s in sols],
        ))
    end
    push!(results, (; c.name, c.kind, c.params, c.Mp, period=P, epochs,
        data=NamedTuple(sort(collect(data), by=first))))
    println("generated: ", c.name)
end

out = joinpath(@__DIR__, "v1_reference.jl")
open(out, "w") do io
    println(io, "# AUTO-GENERATED by generate_v1_reference.jl against PlanetOrbits v1 — do not edit.")
    print(io, "const V1_REFERENCE = ")
    show(io, results)
    println(io)
end
println("wrote ", out)
